#!/usr/bin/env bash
# This script:
# Create a file /var/run/myscript.pid containing the script PID.
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" upon receiving a SIGTERM
# Displays "Y U no love me?!" upon receiving a SIGINT
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM.

sudo touch /var/run/holbertonscript.pid
sudo -C 'echo $$ > /var/run/holbertonscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
