#!/usr/bin/env bash
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
