#!/usr/bin/env bash
#This script is displaying Best School 10 times , but for the
#9th iteration, displays Best School and then Hi on nex line

var=1
while [ $var -le 10 ]
do 
	echo "Best School"
	if [ "$var" = 9 ]
	then
		echo "Hi"
	fi
	(( var++ ))
done
