#!/usr/bin/env bash
#This script loops from 1 to 10

var=1
while [ $var -le 10 ]
do
	if [ $var = 4 ]
	then
		echo "bad luck"
	elif [ $var = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( var++ ))
done
