#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requierements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.copy
sed -i 's/127.0.0.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.copy
cp -f ~/hosts.copy /etc/hosts
